name: my_coach
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_vertexai: ^0.2.2+4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.14
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  pinput: ^5.0.0
  uuid: ^4.4.2
  firebase_app_check: ^0.3.0+4
  flutter_markdown: ^0.7.3+1
  shared_preferences: ^2.3.2
  cloud_firestore: ^5.2.1
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  firebase_storage: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf

  assets:
    - assets/images/
    - assets/svgs/
